## Skeptic Training and Validation Set data preparation for Justification Finetuning

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer

# pd.set_option("display.max_colwidth", None)

In [2]:
model_name = "amazon/MistralLite"

tokenizer = AutoTokenizer.from_pretrained(model_name)
print(f" PAD Token ID is set to - {tokenizer.pad_token_id}")
tokenizer.padding_side = "right"

Downloading (…)okenizer_config.json:   0%|          | 0.00/1.52k [00:00<?, ?B/s]

Downloading tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

Downloading (…)/main/tokenizer.json:   0%|          | 0.00/1.80M [00:00<?, ?B/s]

Downloading (…)cial_tokens_map.json:   0%|          | 0.00/210 [00:00<?, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

 PAD Token ID is set to - 32000

### Loading Labelled data from GPT-4

In [3]:
df = pd.read_csv("data/claims_justification_labels1.csv")

In [4]:
df.head()

,video_id,title,author,description,org_transcript,eng_transcript,image_base64,url,Summary_Claims,Justification,labels
0,FyQiu-o3VaI,IGL share price drop by 10.8%: Know the Reason...,5paisa,Indraprastha Gas share price (IGL) fell 10.84%...,"Hi Guys, IGL की Stock में आज 10% तक का बड़ा फॉ...","""Hi Guys, we have seen a big fall of up to 10%...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAgGBggIDQgIDQ...,https://www.youtube.com/watch?v=FyQiu-o3VaI,The financial influencer claims that the IGL s...,The claim is plausible as the adoption of EVs ...,true
1,TK74cx0p-NM,Nestle India share price jumps by over 1.5% af...,5paisa,Nestle India share price jumped more than 1.5%...,[Music] hi everyone 1.5 Financial results Mar...,[Music] Hi everyone! The financial results for...,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAgGBgcICAgIBw...,https://www.youtube.com/watch?v=TK74cx0p-NM,The financial influencer claims that the finan...,The claim is true if the financial results for...,true
2,70ifhSt5N_c,Wipro Q2 Results Highlights #q2results #shorts,5paisa,Discover the key highlights from Wipro's Q2 FY...,"Hi guys, Vipro ke numbers ek baar phir umeet s...","""Hi guys, Vipro's numbers have once again fall...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAgGBggICAgICA...,https://www.youtube.com/watch?v=70ifhSt5N_c,The financial influencer claims that Vipro's r...,The claims made by the influencer are based on...,neutral
3,zb6dOEuW6qg,Nifty/BankNifty Prediction For Tomorrow for 19...,5paisa,Here you can find the nifty predictions for 19...,पिछले कुछ दिनों में मार्केट्स में ग्रैजूल रिका...,"In the past few days, the markets witnessed gr...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAgGBgkICAgICQ...,https://www.youtube.com/watch?v=zb6dOEuW6qg,The financial influencer claims that the marke...,The claims made by the influencer are based on...,neutral
4,w-neJT7eaGU,Zomato Share Price Surges to 52-Week High: Kno...,5paisa,"On 18-Oct-2023, Zomato share price reached a 5...","Hi everyone, aaj Zomato ke shares ne a 52 week...","""Hi everyone, today Zomato's shares have hit a...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAgGBgcICAgIBw...,https://www.youtube.com/watch?v=w-neJT7eaGU,The financial influencer claims that Zomato's ...,The claim seems plausible as strategic partner...,true

In [5]:
def prepare_prompt(sample):
    claim, justification = sample["Summary_Claims"], sample["Justification"]
    prompt = f"""You are a Financial Contrarian Writer. You are provided with a
Summary of Claims made by financial influencer and your task is to write
justifications for those claims. Claim Summary: {claim}"""
    text = ""
    text += f"<|prompter|>{prompt}</s><|assistant|>{justification}"
    return text

In [6]:
df["text"] = df.apply(prepare_prompt, axis=1)

In [7]:
train_data, test_ds = train_test_split(df, shuffle=True, test_size=0.1, random_state=42)
train_ds, val_ds = train_test_split(train_data, shuffle=True, test_size=0.1, random_state=42)

print(f"Train dataset {len(train_ds)}, and Validation dataset {len(val_ds)}, and Test dataset: {len(test_ds)}")

Train dataset 88, and Validation dataset 10, and Test dataset: 11

In [8]:
train_ds.head()

,video_id,title,author,description,org_transcript,eng_transcript,image_base64,url,Summary_Claims,Justification,labels,text
35,9H5UCpR9uqk,RBI Introduces 50-Year Bonds for the First Tim...,5paisa,This new 50-year bond will be auctioned for Rs...,हे इंडिया के बॉंड मार्केट्स काफी पॉपिलर हो रहे...,"Text: ""Bond markets in India are becoming quit...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAgGBggIDQcICA...,https://www.youtube.com/watch?v=9H5UCpR9uqk,The financial influencer claims that bond mark...,The claim about the introduction of fifty year...,true,<|prompter|>You are a Financial Contrarian Wri...
59,2MhfmuwFYkY,G20 Summit 2023: 3 Key Takeaways #shorts,5paisa,Watch this #short to know the G20 Summit 2023 ...,G20 समित में सारे देशों की सहमते बढ़ने से दुनि...,"""The world is positively surprised by the incr...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAgGBgcICAcIBw...,https://www.youtube.com/watch?v=2MhfmuwFYkY,The financial influencer claims that the G20 s...,The claim about the success of the G20 summit ...,true,<|prompter|>You are a Financial Contrarian Wri...
49,Qaz8rB1iMpc,High Return Stocks - Top-Performing Stocks fro...,5paisa,Let's look at the Best performing Stocks from ...,"Hi everyone, हर रोज हमारे यूट्यूब चानल फाई पैस...","""Hi everyone, every day on our YouTube Channel...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAgGBgcICAgIBw...,https://www.youtube.com/watch?v=Qaz8rB1iMpc,The financial influencer claims that they reco...,The claims made by the influencer are difficul...,neutral,<|prompter|>You are a Financial Contrarian Wri...
40,iAdnPLWBnRU,High Return Stocks - Top-Performing Stocks fro...,5paisa,Let's look at the Best performing Stocks from ...,"Hi everyone, on the daily basis, हम आपसे शेयर ...","""Hi everyone, on a daily basis, we share our b...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAgGBggICAcHCA...,https://www.youtube.com/watch?v=iAdnPLWBnRU,The financial influencer claims to provide dai...,The claims made by the influencer are difficul...,neutral,<|prompter|>You are a Financial Contrarian Wri...
25,ELahYpGKsJ8,Top Sector-wise Stock Picks for ICC Cricket Wo...,5paisa,Following are some sectors that are worth watc...,"Hi, ICC Men's World Cup 2023 शुरू हो चुका है औ...","""Hi, the ICC Men's World Cup 2023 has started ...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAgGBggICAkICA...,https://www.youtube.com/watch?v=ELahYpGKsJ8,The influencer claims that the ICC Men's World...,The claims made by the influencer are plausibl...,true,<|prompter|>You are a Financial Contrarian Wri...

In [9]:
train_ds.text[35]

"<|prompter|>You are a Financial Contrarian Writer. You are provided with a\nSummary of Claims made by financial influencer and your task is to write\njustifications for those claims. Claim Summary: The financial influencer claims that bond markets in India are gaining popularity and the Reserve Bank of India has introduced a new investment option - government securities with a maturity of fifty years. Until now, only ultra long-term duration bonds with a maturity of forty years were available. The influencer also suggests that these bonds are considered the safest option and their demand is increasing. For retail investors, current deals in the secondary market can be attractive, despite limited liquidity for securities. The influencer also suggests that dead mutual funds can be an option in such cases.</s><|assistant|>The claim about the introduction of fifty years maturity government securities by the Reserve Bank of India can be verified by checking the official announcements by the RBI. The claim about the increasing popularity and demand for these bonds is subjective and can vary based on market conditions and investor sentiment. The claim that these bonds are the safest option is generally true as government securities are considered low risk. However, the risk can vary based on the economic stability of the country. The claim about the attractiveness of current deals in the secondary market and the suggestion to consider dead mutual funds are subjective and would depend on individual investor's risk tolerance, investment goals, and market knowledge."

### Saving the train and validation sets

In [10]:
train_ds.to_csv("data/train_skeptic_df.csv", index=False)
val_ds.to_csv("data/val_skeptic_df.csv", index=False)

### Test Set Preparation

In [11]:
test_ds.drop(columns=["text"], inplace=True)

In [12]:
def test_prepare_prompt(sample):
    claim = sample["Summary_Claims"]
    prompt = f"""You are a Financial Contrarian Writer. You are provided with a
Summary of Claims made by financial influencer and your task is to write
justifications for those claims. Claim Summary: {claim}"""
    text = ""
    text += f"<|prompter|>{prompt}</s><|assistant|>"
    return text

In [13]:
test_ds["text"] = test_ds.apply(test_prepare_prompt, axis=1)

In [14]:
test_ds.text[10]

"<|prompter|>You are a Financial Contrarian Writer. You are provided with a\nSummary of Claims made by financial influencer and your task is to write\njustifications for those claims. Claim Summary: The financial influencer claims that Indigo's co-founder Rakesh Gangwal might sell a significant portion in SpiceJet, which led to a 19% increase in SpiceJet's stock. The influencer also claims that SpiceJet is currently facing financial struggles, making it a fourth-rate player in the free trade grounds. The airline is also dealing with issues like supply chain problems, non-availability of engine spare parts, and high competition in the industry.</s><|assistant|>"

In [15]:
test_ds.to_csv("data/test_skeptic_df.csv", index=False)